// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS.DataContext;

#nullable disable

namespace POS.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230110091235_AddToDatabase")]
    partial class AddToDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("POS.DataContext.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_code");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_description");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_category");
                });

            modelBuilder.Entity("POS.DataContext.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_email");

                    b.Property<string>("ClientGender")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_gender");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_name");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("client_company_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_client");
                });

            modelBuilder.Entity("POS.DataContext.DivisionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("DivisionDescription")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("division_description");

                    b.Property<string>("DivisionName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("division_name");

                    b.HasKey("Id");

                    b.ToTable("tbl_division");
                });

            modelBuilder.Entity("POS.DataContext.EmployeeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_email");

                    b.Property<string>("EmployeeGender")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_gender");

                    b.Property<string>("EmployeeJobPosition")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_job_position");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_name");

                    b.Property<string>("EmployeeStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("employee_status");

                    b.HasKey("Id");

                    b.ToTable("tbl_employee");
                });

            modelBuilder.Entity("POS.DataContext.InventarisEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("InventarisBrand")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventaris_brand");

                    b.Property<string>("InventarisCategory")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventaris_category");

                    b.Property<string>("InventarisProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventaris_product_name");

                    b.Property<string>("InventarisStock")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("inventaris_stock");

                    b.HasKey("Id");

                    b.ToTable("tbl_inventaris");
                });

            modelBuilder.Entity("POS.DataContext.ProductEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("ProductCategory")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_category");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_name");

                    b.Property<string>("ProductPrice")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_price");

                    b.HasKey("Id");

                    b.ToTable("tbl_product");
                });
#pragma warning restore 612, 618
        }
    }
}
